apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  name: sops-atlantis-secret
spec:
  suspend: false
  secretTemplates:
    - name: atlantis-secrets
      stringData:
        webhook-secret:
        gh_token:
        gh_user:
        gh_repository: github.com/{account}/*
