apiVersion: v1
kind: ServiceAccount
metadata:
  name: atlantis
  annotations:
    iam.gke.io/gcp-service-account: {global_account}@host_project_id.iam.gserviceaccount.com
automountServiceAccountToken: true
